### PR TITLE
Balance T3 TLL Air

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
T3 Bomber ARM/ CORE / TLL Balanced 
=> For t3 TLL heavy bomber, don't know how much damage by fire after explosion
Balance T3 Gunship & Fighter TLL

**Comment by nixtux** [comment]
https://github.com/n3wm1nd/TA/commit/7c71d84a20420ff422406b58caa9783848aa624d

-- radius		- defines size of sphereical area in which damage is dealt
-- damage		- maximun damage over 1 second that can be dealt to a unit
-- duration		- how long the area damage stays around for (in frames)
-- rangeFall	- the proportion of damage not dealt increases linearly with distance from 0 to rangeFall at the radius
-- timeFall		- the proportion of damage not dealt increases linearly with elapsed time from 0 to timeFall at the duration

**Comment by nixtux** [comment]
btw let me know when you have finished so i can merge in one go

**Comment by nixtux** [comment]
Ohh forget to say the maxing damage dealt by the area_damage_gadget is never reached due to fall off rates

**Comment by skymyj** [comment]
Question : how much frames in 1 seconde ?

**Comment by nixtux** [comment]
30 frames per second

**Comment by skymyj** [comment]
thanks. 
Miss the last commits with shrike

**Comment by skymyj** [comment]
I will redo a proposal

**Pull request merged**
