### PR TITLE
Defiler : Balance AA Weapon

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
#921

**Comment by nixtux** [comment]
I disagree this unit needs a strong AA weapon

**Comment by skymyj** [comment]
At least, just decrease range. 
800 is not necessary to defend. 600 will be better.

**Comment by nixtux** [comment]
I'm fine with this now I've seen them in action

**Comment by skymyj** [comment]
Thanks

**Pull request merged**
