### PR TITLE
Balance XP to morph

### PR DESCRIPTION
**Pull request by skymyj**
Just tested

### CODE REVIEW

**Comment by nixtux** [comment]
Fix typo in old commit then I will merge this

**Comment by skymyj** [comment]
Can you wait. 
I think there is an another.

**Comment by skymyj** [comment]
Ok. It works ! :)

**Comment by nixtux** [comment]
cant merge as i did full whitespace clean up, you need to redo commit

**Comment by skymyj** [comment]
Ok

**Comment by skymyj** [comment]
I will do tomorrow.

**Pull request closed without merging**
