### PR TITLE
Balance Commander wreckage

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
#1076

**Comment by skymyj** [comment]
I dont change the eco battle & standard com. 
I think, we need more opinions (solv, silver, soulraizor, keiji..) to take decision.

**Comment by nixtux** [comment]
Skymyj Supreme Commander are wrong

**Comment by skymyj** [comment]
Where ?

**Comment by skymyj** [comment]
Again conflicts..

**Comment by skymyj** [comment]
I resign to make commits for this subject.

**Pull request closed without merging**
