### PR TITLE
Increased TLL  Burner speed +30%

### PR DESCRIPTION
**Pull request by Senna**
upgrade burner

### CODE REVIEW

**Comment by Gambit99** [comment]
+1 since this makes them just slightly slower than pyros which is appropriate

**Comment by nixtux** [comment]
Let me see what I can do with his animation first otherwise he will look like he is going to shake himself apart

**Comment by Zonkspring** [comment]
+2
- Burner costs almost 2x as much as Pyro
- Has exactly 2x as much DPS ( = same dps/cost)
- Has 1650 hp compared to Pyros 1000 hp ( = worse hp/cost, tho its relative - Burners for same $ as Pyros will suffer less from AOE effects.)
- 5 sec Countdown Selfd, Pyro just 1 sec. 
- Leaves wreckage (= harder to make effective suicide-raids) - Pyro just leaves Debris, less reclaim for enemy.

30% speed boost - to slightly slower than Pyro - is absolutely justified.
I was so far thinking of it as more of a Zeus-like unit (cuz both are called "Assault Kbot") and thought it maybe needs a HP boost, but making it more similar to Pyro is another way of balancing it.
Lets just not do both at same time or it will be op. ;P

Should be renamed to from "Assault Bot" to "Fast Assault Bot" then tho.

**Comment by skymyj** [comment]
As I said, compare pyro and zipper. Pyro enegy cost have to be increased to 3ke or more.
For tllburner, I think the acceleration boost is a good idea. Let speed to 2 and increase maxdamage to 2200.

**Pull request closed without merging**
