### PR TITLE
Balane Cordem vs Bantha

### PR DESCRIPTION
**Pull request by skymyj**
Increase Stats for experimental flammer T3. 
& Now, same destruction than bantha.

### CODE REVIEW

**Comment by nixtux** [comment]
No no no don't change bantha mass, if you see any silly size mass it's for a reason we don't want flying bantha

**Comment by skymyj** [comment]
Should be good a flying bantha :)

**Comment by skymyj** [comment]
When I see : 
impulseboost = 0.12300000339746,
impulsefactor = 0.12300000339746,

Is it for a reason or for fun ?

**Comment by nixtux** [comment]
No just not been rounded down

**Comment by skymyj** [comment]
Next balance will be for shield Kbot.
But I think, they unbalance game... 
Is it possible to have this approch #584

**Pull request merged**
