### PR TITLE
Balance Hyperion

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by Senna** [comment]
Not enought, it needs at least lower speed
sorry even with that changes i lost the fun to keep playing TA HYPERION IS TOTAL OP

**Comment by Senna** [comment]
1.8 too mutch an 300k hp unit
it need 1.5 it got HP BUFFED

**Comment by skymyj** [comment]
sure it's a very strong unit. but 70k Metal cost & can be dguned by com

**Comment by Senna** [comment]
if u buff HP decrease speed, if u decrease HP increase speed this is how it works

**Comment by Senna** [comment]
no it cannot be dguned

**Comment by Senna** [comment]
fix it and i play TA again

**Comment by Senna** [comment]
that is alot better

**Comment by skymyj** [comment]
welcome back on TA :)

**Comment by Senna** [comment]
and about 70k metal, fury needs more to be made at least the first one, it needs almost 80k metal

**Comment by skymyj** [comment]
T2.5 Tank need buff too. Hp 2700=>1900. I suggested delete this unit too.

**Comment by Senna** [comment]
make a new fix release and ill come back

**Comment by Senna** [comment]
yes absolutor needs a nerf too, make a new release and ill be back to TA

**Pull request merged**
