### PR TITLE
Update armpw.lua

### PR DESCRIPTION
**Pull request by skymyj**
Balance unit

### CODE REVIEW

**Comment by skymyj** [comment]
Infantry Balance

**Comment by nixtux** [comment]
raider_resistant = 17.5, is removed why ?

**Comment by skymyj** [comment]
Restored.

I think, we need a new definition for class use. (What is a raider for you ? feature ?)
Is it possible to add Hover Class ?

**Comment by nixtux** [comment]
https://github.com/n3wm1nd/TA/wiki/Unit-Classes

**Pull request merged**
