### PR TITLE
Don't jump from your chair :)

### PR DESCRIPTION
**Pull request by skymyj**
Experimentation. See #584.

### CODE REVIEW

**Comment by skymyj** [comment]
Fixed

**Comment by skymyj** [comment]
Adding Shield bot balance. 
Irritator for next commit. Tonight or tomorrow maybe

**Comment by skymyj** [comment]
I clean 6 files with weapon Jammer.
But I wait before you accept or refuse this request.

**Comment by skymyj** [comment]
When do you think to make next release ?

**Comment by nixtux** [comment]
when all the errors in 99.0 are fixed

**Pull request merged**
