### PR TITLE
TllHairstorm : Proposal for new weapon

### PR DESCRIPTION
**Pull request by skymyj**
Goal : Add very long range for this unit. (same than t3.5 Ship)
+ extra damage vs ship

tested & Work

### CODE REVIEW

**Comment by nixtux** [comment]
Imo reworking heavyimpact and keep this one as it is

**Comment by skymyj** [comment]
This unit is not balanced imho, even if you rework heavyimpact.
- too much HP (to counter)
- cost too high for an artillery
- not energy / shot
- range is too high with T3 balance artillery unit. Or range is too low to be mobile LRPC.

**Comment by nixtux** [comment]
Hailstorm original idea was to be like juggernaut, slow moving high hp with load range weapon

**Comment by skymyj** [comment]
Yes I remember.
But there is already other Kbot for this. (tllblind => less strong but slow & armoured).

**Pull request merged**
