### PR TITLE
Corgala : balance Energy Cost / shot

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
per shot

**Comment by nixtux** [comment]
imo your energycosts per shot are way too high

**Comment by skymyj** [comment]
I know it's high but always less than experimental canon (110 KE / Shot) 
We have a 8K DMG / S (80K DMG per shot)
Maybe 40KE ? But not less please. What do you think ?

**Comment by skymyj** [comment]
Is it possible to have a better visual effect ? Like gold beam ?

**Comment by nixtux** [comment]
Yeah I will handle visuals

**Pull request merged**
