### PR TITLE
Balance AA vehicles

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
Is it possible to change the weapon for hover AA, Kbot T1 AA ? 
Idea is to make just 1 weapon type x 2 & delete "boggle missile"...
Goal : more visibility

**Comment by nixtux** [comment]
Yeah I'm fine with that

**Comment by nixtux** [comment]
You can even clean up arm/coraak if you want

**Comment by skymyj** [comment]
For arm/coraak, I keep the the aa canon.

Question for missile : 
Do I keep just 1 missile weapon for all the weapons list (6~8) ?
Or
Do I keep just 1 missile weapon with the canon AA ?

**Pull request merged**
