### PR TITLE
Balance Riot T3 TLL Kbot : TLLBlind

### PR DESCRIPTION
**Pull request by skymyj**
Nix : If you are agree, can i change the Green laser by a lighting ? 

Thanks

### CODE REVIEW

**Comment by nixtux** [comment]
Any change to lighting needs script altering, will do for next release

**Comment by skymyj** [comment]
Thanks !

**Comment by nixtux** [comment]
I don't agree with the drop in airsightdistance , due to plane speed it needs the original value

**Comment by nixtux** [comment]
Not atm due to https://github.com/n3wm1nd/TA/pull/1222#issuecomment-253300144

**Comment by skymyj** [comment]
done

**Pull request merged**
