### PR TITLE
Update tllbind.lua

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
That's a big jump in damage/dps for a weapon that deals full damage whatever the distance

**Comment by skymyj** [comment]
OK. Didnt know that inflict max damage.
But same balance with increase reload

**Comment by nixtux** [comment]
All Lightning cannon type weapons deal full damage whatever the range, that why tll can be so hard to balance or fight

**Comment by skymyj** [comment]
So, I tested vs corsumo. 
At long range, sumo wins at 40% HP
At short Range, Bind wins at 50% HP.

Very good balanced imho & nice effect

**Comment by nixtux** [comment]
There is no bursts ?

**Comment by skymyj** [comment]
Hey Nix. 
No burst but projectiles.
After test, the projectiles are better => one source, with 3 target. Bursts create "shift" on the side

**Comment by nixtux** [comment]
Seem's so strong

**Comment by skymyj** [comment]
At range > 350, there is 50% random for each projectile to miss target.
So you have : 
- 700 dmg/s at range 350<
- 525 dmg at range 400
- 350 dmg at range 500
- 175 dmg at range 600

Imho it's seems balanced.

**Comment by nixtux** [comment]
Hmm now you have reworked this unit to be sumo counterpart, it was meant to be a corcan counterpart (A very strong one).
Now tll will be lacking with a sniper_resistant unit. As this armorclass need changed to suit the new roll of sumo counterpart.
Check https://github.com/n3wm1nd/TA/blob/master/gamedata/armordefs.lua  raider_resistant

**Comment by nixtux** [comment]
NM i will alter armorclass

**Pull request merged**
