### PR TITLE
Metron Need Hp boost

### PR DESCRIPTION
**Pull request by ghost**
comparing to Krog price need HP boost

### CODE REVIEW

**Comment by ghost** [comment]
[14:12:58] <Casanova> price is good, velocity too (otherwise it would easily OP)
[14:13:40] <Casanova> for me only HP should be at least 60k

**Comment by skymyj** [comment]
Finally Open or Close ?

**Comment by skymyj** [comment]
For HP, I think, we can add a first boost and fix at 45K HP. 
Timebuild is too low. Fix at 230000

**Comment by nixtux** [comment]
Wrong repo see https://github.com/techannihilation/TA/pull/253

**Pull request closed without merging**
