### PR TITLE
Proposal to change armmech (killer) into amphibious

### PR DESCRIPTION
**Pull request by skymyj**
Remplace Missile by torpedo
Increase metal cost & speed 1.2=>1.5

### CODE REVIEW

**Comment by skymyj** [comment]
#1052

**Comment by skymyj** [comment]
Tested

**Comment by nixtux** [comment]
Will need script change also, weapon checks for water depth

**Comment by nixtux** [comment]
Can you do scorpion as its own commit please

**Comment by skymyj** [comment]
Done

**Pull request merged**
