### PR TITLE
Naval Balance

### PR DESCRIPTION
**Pull request by skymyj**
BattleShip T2 Core, second weapon damage increase (less reload).
&  Deleted Laser TLL Ship. totaly Under Powered. Even if we increase stats, there is already an other ship that does the job.

### CODE REVIEW

**Comment by skymyj** [comment]
Add TllCopter (increase energycost) & blade (decrease energy & metal cost). To balance them.

**Comment by nixtux** [comment]
Won't merge tllbats is the correct countpart to arm/corbats

**Comment by skymyj** [comment]
The counterpart to Arm/Corbats is the tllviking, isn't ?
https://github.com/n3wm1nd/TA/wiki/tllviking

There is already an unit than OP (less cost & better stats & laser weapon) this TLL LAser :  https://github.com/n3wm1nd/TA/wiki/tllequalizer

This unit is just useless & too high cost.
https://github.com/n3wm1nd/TA/wiki/tllbats2

**Comment by nixtux** [comment]
My bad your right, will merge

**Comment by skymyj** [comment]
Is it possible to actualise Wiki Nix ?

**Comment by skymyj** [comment]
Or must we wait next release ?

**Comment by nixtux** [comment]
Yeah i will update wiki when I get some free time

**Comment by nixtux** [comment]
Wait till next release, which will be with next engine release

**Pull request closed without merging**
