### PR TITLE
Balance units

### PR DESCRIPTION
**Pull request by skymyj**
See commits

### CODE REVIEW

**Comment by skymyj** [comment]
All tested

**Comment by nixtux** [comment]
No its not there is a typo in there, and I don't agree with change for all terrain tanks

**Comment by skymyj** [comment]
"No its not there is a typo in there" => I don't understand

**Comment by nixtux** [comment]
You said you tested it but I've found a typo in armpers, check your change for rgb color

**Comment by skymyj** [comment]
Deleted all terrain change.

**Comment by skymyj** [comment]
If you are Ok, is it possible to mege it ? 
thanks

**Comment by skymyj** [comment]
Adding : 

Balance AA Sam

AA madsam.lua & packo.lua = 400 dmg/s with same damage for all classes
Bomb resistant :
- Add more visibility on damage / s
- 550 dmg/s vs air, 700dmg/s vs bomber & 400dmg/s vs flak resistant
- I let Riffle effect
For version1 of bomb resistant : 
- I let Continue shot with more visibility
- 700 dmg/s vs air, 800dmg/s vs bomber & 600dmg/s vs flak resistant

**Comment by nixtux** [comment]
Change shiva weapon model back and I will merge it

**Comment by skymyj** [comment]
OK I will. 
Can I keep :
- guidance = true
- Not limited target class (vtol..)
- Damage & Range 
? Thanks

**Comment by nixtux** [comment]
Only change weapon model back and I'm happy

**Comment by skymyj** [comment]
Done.

**Pull request merged**
