### PR TITLE
Spider T2 : Weapon effect change (same balance)

### PR DESCRIPTION
**Pull request by skymyj**
Corcan effect weapon
#923

### CODE REVIEW

**Comment by skymyj** [comment]
tested

**Comment by nixtux** [comment]
But aoe is reduced could effect balance slightly imo (will test before merge)

**Comment by skymyj** [comment]
Did you have tested ?

**Comment by skymyj** [comment]
So, Can I Close this commit or do you merge ?

**Comment by nixtux** [comment]
Close

**Pull request closed without merging**
