### PR TITLE
Update nsaagriz.lua

### PR DESCRIPTION
**Pull request by Kaka5hi**
too low, i know you try it make slowly, but its rly slow reload

### CODE REVIEW

**Comment by nixtux** [comment]
Can't merge anyways your repo is out of date, you need to allways pull from main repo before making any changes

**Comment by Kaka5hi** [comment]
i mess up something, deleted repository and forked again - not good idea?
how to update? need delete everytime?

pls delete this - Update nsaagriz.lua #1085

**Comment by skymyj** [comment]
You have to create a new branch. 
Go to : https://github.com/n3wm1nd/TA/blob/master/units/nsaagriz.lua 
And use Edit tool. You will automately create a new branch.

**Comment by Kaka5hi** [comment]
yes thx, hmm not sure maybe last time i did propably from my repo not nix repo thats why I was out of date i guess :)

**Pull request closed without merging**
