### PR TITLE
Option 1 For Eco Strategy

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
I change : 
- delete all helper for Commander.
- delete abuilderlvl2 & cbuilderlvl2 from Eco Commander
- Remplace Panel Menu from helper into abuilderlvl2 & cbuilderlvl2 (with new add : Pewee / AK Canon, Adv HLT, Torpedo, Rocket Bot1, Medium Tank1)
- Decrease Cost from Marvin & Corfred (900=>700). Delete All HLT & Torpedo. New add : Sea Nano & Cons & Sub Cons veh

**Comment by skymyj** [comment]
Ok, I have done.

**Comment by nixtux** [comment]
What do you need my end?

**Comment by skymyj** [comment]
You can merge.

**Comment by nixtux** [comment]
Ok but Iirc you need some weapons added?

**Comment by nixtux** [comment]
Just 1 weapon per units?

**Comment by skymyj** [comment]
Wich unit ? And which xweapon you talk about ?

**Pull request merged**
