### PR TITLE
Jaguard - Proposal for New Design. (~Same Balance)

### PR DESCRIPTION
**Pull request by skymyj**
Not touching to StarBurst. (decrease aoe ) => same than bantha.
Decrease Beam Laser => same then bantha (= decrease like 350dmg/s & range 950 => 800)
Remplace gauss canon by a Multi Gauss with 6 burst. (450dmg/s => 1100 dmg/s with 900 => 625 range)
SprayAngle balances damage / s with some burst lost.

Before, it was a long range unit (with best weapon to 950 at 850 damage/s). Now it's more an assault Mech like Macross for Core.
Tested !
thanks.

### CODE REVIEW

**Comment by skymyj** [comment]
#1009

**Comment by nixtux** [comment]
Does the weapon effect for cannon even match now with that velocity increase ?

**Comment by skymyj** [comment]
It's between krogoth and pewee visual effect. Less speed than krogoth. 
3 burts from each arm in same time  to have 6 bursts every 1.5 second. 
The speed gives dynamic shot. But same effect than before.

**Comment by skymyj** [comment]
Did you have tested ?

**Pull request merged**
