### PR TITLE
Clean Morph.lua & balance Tech & Time for Geo & Add Morph

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
1st Goal : No need to tech to have big units... You can also do battles to have good morphing unit.
So, no need to have Tech research or T2/T3 Lab for Battle Unit to morph.

2st Goal : Give more time to morph into Adv Geo. 

3st : A Geo can morph into Adv Geo or Second Adv Geo (Behemoth).

**Comment by skymyj** [comment]
Adding armOrco for Vengence. 

Do we add T3 Razorback into T4 Mega Razorback ? 
(same for Core)

**Comment by nixtux** [comment]
Why remove geo<> behemoth morphs?  It's was a feature

**Comment by skymyj** [comment]
Because, it's a choice to do with T1 tech. Between adv geo or Behemoth. 
If you chose Behemoth, next you can morph into behemoth1. 
Imo, adv geo can't morph into Behemoth.

**Comment by skymyj** [comment]
To difficult & too many options kill ergonomy & strategy. 
It was always between, hazardous (with big explosion) & weapon. 
Too easy to turn your hazardous (adv geo) into behemoth. 
(same for arm with fortified geo)

**Comment by nixtux** [comment]
Yeah add razorback and core counterparts morph and I will merge :)

**Comment by skymyj** [comment]
But i have to do test with good xp

**Comment by nixtux** [comment]
Pff untested chnage please fix it  -- [f=-000001] Error: LuaRules::RunCallIn: error = 2, Initialize, [Internal Lua error: Call failure] error = 2, LuaRules/gadgets.lua, error = 3, LuaRules/Configs/morph_defs_techa.lua, [string "LuaRules/Configs/morph_defs_techa.lua"]:852: '}' expected (to close '{' at line 20) near 'if'

**Pull request merged**
