### PR TITLE
Increased tll thunder speed  15%

### PR DESCRIPTION
**Pull request by Senna**

### CODE REVIEW

**Comment by nixtux** [comment]
Senna you increased acceleration by 400% unacceptable, not even armflash has that sort of speed https://github.com/n3wm1nd/TA/blob/master/units/armflash.lua

I will accept a max increase of 0.035

**Comment by nixtux** [comment]
Also also I think you need a new calculator as 15% increase of 0.8 is 0.92 not 1.1, won't be merging this due to hidden changes

**Comment by Gambit99** [comment]
Senna your proposed changes tend to have an upsetting effect.

It is easy to add another incremental change to a subsequent patch if it is needed, but it is difficult (and harder on the players) if you have to go back and reverse a large change because it caused an unforeseeable side effect on the game. This "sledgehammer" approach will cause large balance swings and much dissatisfaction among the players.

**Comment by Gambit99** [comment]
Keep in mind though that acceleration only affects the rate at which the unit gets up to full speed, and so makes it feel more responsive. It doesn't affect the maximum velocity. For slow units, a large acceleration change makes them much easier to handle and micro-manage. The other parameter that determines micro-manageability is turn rate. Both of these are usually set lower for vehicles.

**Comment by SoulRaiZor** [comment]
if u want to increase something by 15% just make x*1,15

**Comment by Senna** [comment]
oh my bad

**Pull request closed without merging**
