### PR TITLE
Upgrade Medium Vanguard Buildtime decreased by 30%

### PR DESCRIPTION
**Pull request by Senna**

### CODE REVIEW

**Comment by nixtux** [comment]
38218 * 0.7 == 26,752.6

**Comment by Senna** [comment]
is not a 30% fix ,its around 30%

**Comment by Gambit99** [comment]
I support this, It took me around 4 minutes to build once with a single assistant. Enemies had T2 coming out already!

**Comment by skymyj** [comment]
+1 with this issues

**Pull request closed without merging**
