### PR TITLE
See #736

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
Actually, there are Tachion1 & Doomsdy1, that there are useless with t4.
Maybe delete them from T3 cons cruiser too. (hardener nano ca nconstruct them).
Let T3/T4 canon for T2 constructor & delete them from engineerer. 
Add  Tachion & Doomsdy, for engineerer.

**Comment by skymyj** [comment]
I don't understand why, there is a conflict.

**Comment by nixtux** [comment]
I can merge it from command line but can't do that till later

**Comment by skymyj** [comment]
OK. Fine for me. But I don't understand how conflicts did happen ?

**Comment by skymyj** [comment]
Clean Adv veh, air, kbot, hover. 
Delete weapon from them. (except for hover. they don't have engineerer).

Next point : 
- have to add long range missile for all engineerer.
- have to clean Adv water (just changing order)

**Comment by skymyj** [comment]
& Except Anti T3/T4 weapon

**Comment by skymyj** [comment]
Find a way to pull without coflicts.
I clone & I will resent with new TA file.

**Comment by skymyj** [comment]
I let you pull if you are ok with line command. 
(too much work for me to sent file 1 by 1).

**Comment by skymyj** [comment]
I let you pull if you are ok with line command. 
(too much work for me to sent file 1 by 1).

**Comment by skymyj** [comment]
There will be some conflicts cause you have merged other request before this. 
So I will close & remerge a final request with all others commits.

**Pull request closed without merging**
