### PR TITLE
T3 AA Balance.

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by nixtux** [comment]
Why remove badTargetCategory = [[MEDIUMVTOL SMALLVTOL TINYVTOL]], it's needed so t3 AA target large units first

**Comment by skymyj** [comment]
Hmm. Ok. I didn't know why there is this option.
I will correct.

**Comment by nixtux** [comment]
So why remove it, if you don't know what it does :)

**Comment by skymyj** [comment]
Yes, I know :) 
I like experiment.
Fixed.

**Pull request merged**
