### PR TITLE
Increase Range for jumpbot.

### PR DESCRIPTION
**Pull request by skymyj**
Balance reload time for commanders

### CODE REVIEW

**Comment by skymyj** [comment]
#1022

**Comment by skymyj** [comment]
closed to dodge conflicts with other merge (#1024)

**Comment by nixtux** [comment]
He was designed to be able to jump up cliffs etc, not long distance that increase is way way too much imo, would be so op imo

**Comment by skymyj** [comment]
We can test at 500 Range. 
We will see.

**Comment by skymyj** [comment]
After testing.
500 range is a way too low.
750 is very good.
I don't think, it's a op unit. (except maybe for "techno lands" type map)

**Comment by skymyj** [comment]
Nix, do you xant to merge it ? 
Range 500 for JetPackKbot is balanced imo. 

More important, we could have a balance for jump commander.

**Comment by skymyj** [comment]
Agree or not for these commits ?

**Comment by nixtux** [comment]
I will Merge if you reduce range from 500>400, that's still an increase of 150 range.

**Pull request merged**
