### PR TITLE
Balance & rework units

### PR DESCRIPTION
**Pull request by skymyj**

### CODE REVIEW

**Comment by skymyj** [comment]
Leave 3s for standar commanders

**Comment by skymyj** [comment]
Is it ok for you Nix ? 
Or Do I leave changes for Weapon Bind TLL ?

**Comment by nixtux** [comment]
Leave it for now, as for that weapon effect to match other tll units I need to do work on the script and I don't have time atm, working on something else atm

**Comment by skymyj** [comment]
Done

**Comment by nixtux** [comment]
I thought I said no morph for tll

**Comment by skymyj** [comment]
I didn't remember it. 
But it can motive players to rush more with T1 unit.
The morph are >0.50 xp. & it will be not often used.

**Comment by skymyj** [comment]
Tll Units in morph file deleted. 
Balance heavy Hover.
Add commanders damage for Pitbull & Manda.
Delete armvisit hover => Lighting hover do already the job.

**Comment by skymyj** [comment]
Is it ok for you nix ?

**Comment by skymyj** [comment]
On Version x.6, there is a bug with TLL T3 Lab. 
We need to fix it quickly on a new version.
https://github.com/skymyj/TA/commit/9f0344f6e4973c10a4fbfc27f55f88d4b28cef24

**Comment by nixtux** [comment]
Why do you allways add to the same pull request, it make it so hard to read through and slow down the process, if there are thing I disagree with, which there a many in this pull request

**Comment by skymyj** [comment]
I didn't know make few pull request with Turtoise & GitHub. 
(I know with https://github.com but it's one request for each files..)
Is it a command line ? Help

**Pull request closed without merging**
