### PR TITLE
Update cnanotower.lua

### PR DESCRIPTION
**Pull request by skymyj**
#898

### CODE REVIEW

**Comment by nixtux** [comment]
Hmm arm/core nanotowers were supposed to have slight differences arm longer range slower build power, core lower range larger buildpower, sky did you set both tower to have same range at some point

**Comment by skymyj** [comment]
YES. Both at 1000 range. 
Now, I can change Range Arm with range at 1200 & Core at buildpower at 1400

**Comment by nixtux** [comment]
why change sightdistance ?

**Comment by skymyj** [comment]
Cause, I think you have to see the place to build structures.

**Comment by skymyj** [comment]
So ?

**Pull request closed without merging**
