### PR TITLE
Balance SEA T3

### PR DESCRIPTION
**Pull request by skymyj**
Change Order for T3 LAB.
Decrease Cost OF T3 LAB. 
Decrease Power from Flag et Super BattleShip.
Decrease Cost of Flag.
Increase Range from T2.5 BattleShip (& decrease damage)
Clean Files

### CODE REVIEW

**Comment by nixtux** [comment]
Why remove storage from t3 ships and energy per shot, make no sense to me why you did this

**Comment by skymyj** [comment]
For storage, I try to clean all units to delete energy produced & used & storage. 
But I'm fine to let them. 1000 storage will not change the balance of the game. Just have more visibility for global storage. Imho, Only storage structure should storage M & E.

For Energy per shot, I think, only energy weapon (laser) should cost energy. Same for Bertha (plasma enriched). For a classic plasma shot = not cost energy. Actually Flagship cost 0 KE / s

But I can restore if you don't agree.

**Comment by nixtux** [comment]
I think plasma cannons should have energy per shot, and I also want storage added back to units it's needed imo, and the cleaning of energy and metal useage/produced should not happen for now (I need think about that more)

**Comment by skymyj** [comment]
Fixed.

**Comment by nixtux** [comment]
Not Fixed you didnt revert all energystorage chnages ot e/m wont morge

**Comment by skymyj** [comment]
Forgotten ARM/COR HCAR. 
Fixed now.

**Comment by nixtux** [comment]
All of them not just t3 ones, I still see some removed

**Comment by skymyj** [comment]
Sory for this forgetfulness

**Comment by nixtux** [comment]
You still missed armbc and tll shield gen (storage is needed there or shield won't function correctly)

**Comment by nixtux** [comment]
You still missed armbc and tll shield gen (storage is needed there or shield won't function correctly)

**Comment by skymyj** [comment]
I don't understand. 
On n3wm1nd, there is 0 in storage for armbc. I added 500 to balance with other T3 Ships.
On last commit : energystorage = 1800 for tllfgate & I didn't touch tllgate. Energystorage = 1800.

**Comment by skymyj** [comment]
is it possible for arm/core Bats, to fire in continue ? (I didn't found the good setting) 
Actually, after have shot the third plasma, there is a latency/waiting  before the next shot like behemoth.

**Pull request merged**
