### PR TITLE
Balance :

### PR DESCRIPTION
**Pull request by skymyj**
- Balance Units
- Rework Akmech beam laser
- T3 Long range (fix to 1400)
- HLT SEA LASER
- TLL Unit cost (with respecting metal focus)
- Bertha Mobile & structure
- Lock blade.lua with T2 RC
- Change order for Air T2 aircraft.

### CODE REVIEW

**Comment by skymyj** [comment]
Is it ok for you ? Or do you want I change somes values ?

**Comment by nixtux** [comment]
Can you add a detailed list of changes to version.txt

**Comment by skymyj** [comment]
Sure. I will tomorrow

**Comment by skymyj** [comment]
Added version.txt

**Comment by nixtux** [comment]
Next time add changes to top of version.txt, so it clearer for players which change is in which release

**Pull request merged**
