### PR TITLE
Clean up Jammers

### PR DESCRIPTION
**Pull request by skymyj**
Not tested

### CODE REVIEW

**Comment by skymyj** [comment]
Adding New structures for XXXcom7 : #584
Balance irritator.
Add new morphing for TLL.

**Comment by nixtux** [comment]
Tll should not have morph

**Comment by skymyj** [comment]
I know. I'm ok for TLL plasma (stronger than ARM/CORE). 
But if you take the AA turet, it will change nothing except have more balance. Same for TLL T2 laser.

**Comment by skymyj** [comment]
#724 => what is your mind on this topic ?

**Comment by nixtux** [comment]
Can't merge you need to update your branch first

**Comment by skymyj** [comment]
Don't understand why here is a conflict. 
I will close & recreate a merge. 
Finally I don't modify the TLL change. Cause, Arm/Core plasma artillery can now morph into T2. I balanced T2 plasma artillery.

**Pull request closed without merging**
