### PR TITLE
Units balance

### PR DESCRIPTION
**Pull request by skymyj**
Units Balance for : 
- Champion Issues https://github.com/n3wm1nd/TA/issues/533
- Seahook Issues  (transport t2 core) https://github.com/n3wm1nd/TA/issues/601
- Blade Issues https://github.com/n3wm1nd/TA/issues/563
- Pelican Issues https://github.com/n3wm1nd/TA/issues/594
- Krypto Issues https://github.com/n3wm1nd/TA/issues/595
- T3 Sniper Issues : https://github.com/n3wm1nd/TA/issues/520
- Menacer Issues  https://github.com/n3wm1nd/TA/issues/529

### CODE REVIEW

**Comment by nixtux** [comment]
There all fine apart from Grims change as damage to experimental units is default damage x4 and you only adjusted one of the experimental armor .

**Comment by nixtux** [comment]
Also blade? You adjusted idle time not max damage

**Comment by skymyj** [comment]
Sorry for blade. 2400 HP & Idle time to 1800. I will fix. 

For, T3 grim. Is it possible to make damage x 2 & not 4 ? 
Can I wrote : 



damage = {
commanders = 3000,
default = 20000,
experimental_land = 40000,
experimental_ships = 40000,
sniper_resistant = 7500,
subs = 5,

- I will make changes for CorProt (sniper). 
Time to reload = 10s. I just will decrease damage a little (10%)

**Comment by nixtux** [comment]
Ok

**Pull request closed without merging**
